language: python
sudo: false
cache:
  pip: true
  yarn: true
python:
  - "3.5"
  - "3.6"
env:
  - TRAVIS_NODE_VERSION="4"
before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip freeze
  - yarn
script:
  - node_modules/.bin/gulp jshint
  - isort --check-only --recursive openslides_protocol tests
  - flake8 openslides_protocol tests
  - PYTHONPATH=./ DJANGO_SETTINGS_MODULE='tests.settings' openslides test
